name: runke-toolbox
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - PySide6
      - openpyxl
      - pymupdf
      - PyYAML
      - pytest
      - Pillow
      - pylibdmtx
      - pytesseract
